# Generated by Django 5.0.6 on 2024-06-03 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_userprofile_user_alter_userprofile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='user',
        ),
    ]
