# Generated by Django 5.0.6 on 2024-06-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_portfolio_user_profile_alter_project_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, upload_to='project_images/'),
        ),
    ]
